linters:
  enable:
    - gofmt
    - govet
    - gosimple
    - staticcheck
    - errcheck
    - ineffassign
    - typecheck
    - gocritic
    - revive
    - gosec
    - unconvert
    - goconst
    - gocyclo
    - goimports
    - misspell
    - prealloc
    - exportloopref
    - bodyclose
    - noctx

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gosec:
    excludes:
      - G204  # Subprocess launched with variable
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck 